module.exports = {
	singleQuuote: true,
	trailingComma: 'all',
	arrowParens: 'always',
	bracketSameLine: false,
	bracketSpacing: false,
	embeddedLanguageFormatting: 'auto',
	htmlWhitespaceSensitivity: 'css',
	insertPragma: false,
	jsxSingleQuote: false,
	printWidth: 120,
	arrowFunctionParens: 'always',
	proseWrap: 'preserve',
	quoteProps: 'consistent',
	requirePragma: false,
	semi: true,
	singleQuote: true,
	useTabs: true,
	vueIndentScriptAndStyle: false,
	tabWidth: 2,
	endOfLine: 'auto',
};
